# Generated by Django 5.0.6 on 2024-06-20 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['created']},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='DataCad',
            new_name='created',
        ),
    ]
